@Enrollment_HostAddress = http://localhost:5184

### Get all available courses
GET {{Enrollment_HostAddress}}/courses
Accept: application/json

### Add a new course
POST {{Enrollment_HostAddress}}/courses/add
Content-Type: application/json
{
    "Code": "STDISCM",
    "Units": 3,
    "Capacity": 30,
    "InstructorId": 1,
    "StudentIds": []
}

### Enroll a student in a course
POST {{Enrollment_HostAddress}}/courses/enroll
Content-Type: application/json
{
  "CourseId": 1,
  "StudentId": 1
  "CourseCode": "STDISCM""
}

